# Site settings
title:          Dominic Prestifilippo
description:    "Working at the intersection of businesses and their customers to improve the value for both."
url:            "https://dpresto.github.io"

# Author
author:
  name:         Dominic Prestifilippo
  url:          https://dpresto.github.io
  email:        dpresto@gmail.com

# Social
instagram:      _dominicp
twitter:        _dominicp

# Collections
collections:    
  work:
    output:         true
    permalink:      /:collection/:title

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks and Pages
permalink:      pretty
paginate:       5
include:        ["_pages"]
homepage:       /index.html

# Set posts to unpublished by default
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      published: false  # This will hide all posts by default